'use client';

import { useState, useEffect } from 'react';

/**
 * View All Generated Images - Live Progress
 * Shows all images generated by batches in real-time
 */

interface ImageData {
  url: string;
  batch: number;
  index: number;
}

export default function ViewAllGeneratedPage() {
  const [images, setImages] = useState<ImageData[]>([]);
  const [loading, setLoading] = useState(true);
  const [lastUpdate, setLastUpdate] = useState<Date>(new Date());
  const [autoRefresh, setAutoRefresh] = useState(true);

  const fetchGeneratedImages = async () => {
    try {
      const response = await fetch('/api/get-generated-images');
      if (response.ok) {
        const data = await response.json();
        setImages(data.images || []);
        setLastUpdate(new Date());
      }
    } catch (error) {
      console.error('Error fetching images:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchGeneratedImages();
  }, []);

  useEffect(() => {
    if (!autoRefresh) return;

    const interval = setInterval(() => {
      fetchGeneratedImages();
    }, 10000); // Refresh every 10 seconds

    return () => clearInterval(interval);
  }, [autoRefresh]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-blue-50 p-8">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">
            📸 Images Générées en Temps Réel
          </h1>
          <p className="text-lg text-gray-600">
            Suivi de la génération des batches - Rafraîchissement automatique
          </p>
        </div>

        {/* Stats & Controls */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-8">
          <div className="flex items-center justify-between">
            <div className="flex gap-8">
              <div>
                <p className="text-sm text-gray-600 mb-1">Images générées</p>
                <p className="text-3xl font-bold text-blue-600">{images.length}</p>
              </div>
              <div>
                <p className="text-sm text-gray-600 mb-1">Dernière mise à jour</p>
                <p className="text-lg font-medium text-gray-900">
                  {lastUpdate.toLocaleTimeString('fr-FR')}
                </p>
              </div>
              <div>
                <p className="text-sm text-gray-600 mb-1">Objectif</p>
                <p className="text-lg font-medium text-gray-900">30+ images</p>
              </div>
            </div>

            <div className="flex gap-4">
              <button
                onClick={() => setAutoRefresh(!autoRefresh)}
                className={`px-4 py-2 rounded-lg font-medium transition ${
                  autoRefresh
                    ? 'bg-green-100 text-green-700 border-2 border-green-500'
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                }`}
              >
                {autoRefresh ? '🟢 Auto-Refresh ON' : '⏸️ Auto-Refresh OFF'}
              </button>
              <button
                onClick={fetchGeneratedImages}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 font-medium transition"
              >
                🔄 Rafraîchir maintenant
              </button>
            </div>
          </div>

          {/* Progress Bar */}
          <div className="mt-6">
            <div className="flex items-center justify-between mb-2">
              <span className="text-sm font-medium text-gray-700">
                Progression vers 25 images (minimum pour LoRA)
              </span>
              <span className="text-sm font-medium text-gray-700">
                {Math.min(100, Math.round((images.length / 25) * 100))}%
              </span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-4 overflow-hidden">
              <div
                className={`h-4 rounded-full transition-all duration-500 ${
                  images.length >= 25 ? 'bg-green-500' : 'bg-blue-600'
                }`}
                style={{ width: `${Math.min(100, (images.length / 25) * 100)}%` }}
              />
            </div>
          </div>
        </div>

        {/* Status Messages */}
        {images.length < 20 && (
          <div className="bg-orange-50 border border-orange-200 rounded-lg p-4 mb-8">
            <p className="text-orange-800">
              ⏳ Génération en cours... Il te faut encore <strong>{20 - images.length} images minimum</strong> pour continuer.
            </p>
          </div>
        )}

        {images.length >= 20 && images.length < 25 && (
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-8">
            <p className="text-blue-800">
              ✅ Tu as assez d&apos;images pour un training test ! Mais <strong>{25 - images.length} images de plus</strong> seraient idéales.
            </p>
          </div>
        )}

        {images.length >= 25 && (
          <div className="bg-green-50 border border-green-200 rounded-lg p-4 mb-8">
            <p className="text-green-800 font-semibold">
              🎉 Excellent ! Tu as {images.length} images. C&apos;est parfait pour le training LoRA !
            </p>
            <a
              href="/select-training"
              className="inline-block mt-3 px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 font-semibold transition"
            >
              ➡️ Aller à la sélection finale
            </a>
          </div>
        )}

        {/* Images Grid */}
        {loading && images.length === 0 ? (
          <div className="text-center py-12">
            <div className="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mb-4"></div>
            <p className="text-gray-600">Chargement des images...</p>
          </div>
        ) : images.length === 0 ? (
          <div className="text-center py-12">
            <p className="text-xl text-gray-600 mb-4">Aucune image générée pour le moment</p>
            <p className="text-gray-500">Les images apparaîtront ici au fur et à mesure de la génération</p>
          </div>
        ) : (
          <>
            <h2 className="text-2xl font-bold text-gray-900 mb-6">
              Images Générées ({images.length})
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
              {images.map((img, index) => (
                <div
                  key={index}
                  className="relative rounded-lg overflow-hidden border-2 border-gray-200 hover:border-blue-400 transition group"
                >
                  <div className="aspect-[4/5] relative bg-gray-100">
                    <img
                      src={img.url}
                      alt={`Generated ${index + 1}`}
                      className="w-full h-full object-cover"
                      loading="lazy"
                    />
                  </div>
                  <div className="absolute top-2 left-2 bg-black/70 text-white px-2 py-1 rounded text-xs font-medium">
                    Batch {img.batch}
                  </div>
                  <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-2">
                    <p className="text-white text-xs font-medium">#{index + 1}</p>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}

        {/* Info Box */}
        <div className="mt-8 bg-blue-50 border border-blue-200 rounded-lg p-6">
          <h3 className="font-semibold text-blue-900 mb-3">ℹ️ Comment ça marche ?</h3>
          <ul className="space-y-2 text-blue-800 text-sm">
            <li>✅ Cette page se rafraîchit automatiquement toutes les 10 secondes</li>
            <li>✅ Les nouvelles images apparaissent au fur et à mesure de la génération</li>
            <li>✅ Minimum recommandé: <strong>20-25 images</strong> pour un training LoRA</li>
            <li>✅ Une fois terminé, tu iras sur <strong>/select-training</strong> pour sélectionner les meilleures</li>
          </ul>
        </div>
      </div>
    </div>
  );
}

